import { Menu } from 'lucide-react'
import Link from 'next/link'

import Logo from '@/components/icons/logo'
import { Button } from '@/components/ui/button'
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet'
import UserButton from '@/components/user-button'

import { type Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: {
		default: 'shop.co',
		template: '%s • shop.co'
	},
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default function AdminLayout({
	children
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			lang='en'
			className={inter.className}
		>
			<body>
				<div className='flex min-h-screen w-full flex-col'>
					<header className='sticky top-0 flex h-16 items-center justify-between gap-4 border-b px-4 md:px-6 bg-white/80 dark:bg-black/80 backdrop-blur-sm shadow-sm'>
						<nav className='hidden flex-col gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6'>
							<Link
								href='#'
								className='flex items-center gap-2 text-lg font-semibold md:text-base'
							>
								<Logo width={70} />
							</Link>
							<Link
								href='#'
								className='text-foreground transition-colors hover:text-foreground'
							>
								Dashboard
							</Link>
							<Link
								href='#'
								className='text-muted-foreground transition-colors hover:text-foreground'
							>
								Orders
							</Link>
							<Link
								href='/dashboard/products'
								className='text-muted-foreground transition-colors hover:text-foreground'
							>
								Products
							</Link>
							<Link
								href='#'
								className='text-muted-foreground transition-colors hover:text-foreground'
							>
								Customers
							</Link>
							<Link
								href='#'
								className='text-muted-foreground transition-colors hover:text-foreground'
							>
								Reviews
							</Link>
						</nav>
						<Sheet>
							<SheetTrigger asChild>
								<Button
									variant='outline'
									size='icon'
									className='shrink-0 md:hidden'
								>
									<Menu className='h-5 w-5' />
									<span className='sr-only'>Toggle navigation menu</span>
								</Button>
							</SheetTrigger>
							<SheetContent side='left'>
								<nav className='grid gap-6 text-lg font-medium'>
									<Link
										href='#'
										className='flex items-center gap-2 text-lg font-semibold md:text-base'
									>
										<Logo width={70} />
									</Link>
									<Link
										href='#'
										className='hover:text-foreground'
									>
										Dashboard
									</Link>
									<Link
										href='#'
										className='text-muted-foreground hover:text-foreground'
									>
										Orders
									</Link>
									<Link
										href='/dashboard/products'
										className='text-muted-foreground hover:text-foreground'
									>
										Products
									</Link>
									<Link
										href='#'
										className='text-muted-foreground hover:text-foreground'
									>
										Customers
									</Link>
									<Link
										href='#'
										className='text-muted-foreground hover:text-foreground'
									>
										Reviews
									</Link>
								</nav>
							</SheetContent>
						</Sheet>

						<UserButton />
					</header>
					{children}
				</div>
			</body>
		</html>
	)
}
